# CHALLENGE 7: Write a program that downloads the historical data for any company in the world....

from urllib import request

# Create a variale and store the link for the csv file we want to downlooad....
goog_stockdata = "https://query1.finance.yahoo.com/v7/finance/download/GOOG?period1=1559067924&period2=1590690324&interval=1d&events=history"


def download_stock_data(csv_url):             # Create a function for the csv file...
    response = request.urlopen(csv_url)       # Connect to the url of the csv on the web...
    csv = response.read()
    csv_strname = str(csv)                    # Save the csv as a string...
    lines = csv_strname.split("\\n")          # Makes the files to appear as in rows and columns.......
    dest_url = r"googhistory.csv"             # Saves the file name into a destination in our computer.....
    fv = open(dest_url, "w")                  # Creates/opens the csv file....

    for line in lines:
        fv.write(line + "\n")                # writes to the csv file
    fv.close()


download_stock_data(goog_stockdata)
